name: Build Windows (Release)

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build QtScrcpy
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64
        cmake --build . --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: QtScrcpy-Windows-Release
        path: |
          output/x64/Release/QtScrcpy.exe
          output/x64/Release/*.dll
          output/x64/Release/sndcpy/
          output/x64/Release/keymap/
