name: Windows Build

on:
  push:
    branches: [ main ]
    paths:
      - 'QtScrcpy/**'
      - '!QtScrcpy/res/**'
      - '.github/workflows/windows.yml'
      - 'ci/win**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Windows x64
    runs-on: windows-2022

    env:
      target-name: QtScrcpy
      vcvarsall-path: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat'
      vcinstall-path: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC'
      qt-ver: '5.15.2'
      qt-arch: 'win64_msvc2019_64'
      qt-arch-install: 'msvc2019_64'
      msvc-arch: 'x64'
      qt-install-path: ${{ github.workspace }}/5.15.2
      plantform-des: win

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v4
        with:
          path: ${{ env.qt-install-path }}/${{ env.qt-arch-install }}
          key: ${{ runner.os }}/${{ env.qt-ver }}/${{ env.qt-arch }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v4.1.1
        with:
          version: ${{ env.qt-ver }}
          target: desktop
          arch: ${{ env.qt-arch }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Generate version
        shell: cmd
        run: python ci\generate-version.py

      - name: Build MSVC x64
        shell: cmd
        env:
          ENV_VCVARSALL: ${{ env.vcvarsall-path }}
          ENV_QT_PATH: ${{ env.qt-install-path }}
        run: call "ci\win\build_for_win.bat" RelWithDebInfo x64

      - name: Get version tag
        shell: bash
        id: get-version
        run: echo "version=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Package
        id: package
        shell: powershell
        env:
          ENV_VCVARSALL: ${{ env.vcvarsall-path }}
          ENV_VCINSTALL: ${{ env.vcinstall-path }}
          ENV_QT_PATH: ${{ env.qt-install-path }}
        run: |
          $publish_name = "${{ env.target-name }}-${{ env.plantform-des }}-x64-${{ steps.get-version.outputs.version }}"
          cmd.exe /c "ci\win\publish_for_win.bat x64 ..\build\$publish_name"
          Compress-Archive -Path "ci\build\$publish_name" -DestinationPath "ci\build\$publish_name.zip" -Force
          echo "package-name=$publish_name" >> $env:GITHUB_OUTPUT

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.package.outputs.package-name }}
          path: ci\build\${{ steps.package.outputs.package-name }}

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ci\build\${{ steps.package.outputs.package-name }}.zip
          asset_name: ${{ steps.package.outputs.package-name }}.zip
          tag: ${{ github.ref }}
          overwrite: true
