name: Windows
# è§¦å‘è§„åˆ™è¯¦è§£ https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on: 
  push:
    paths:
      - 'QtScrcpy/**'
      - '!QtScrcpy/res/**'
      - '.github/workflows/windows.yml'
      - 'ci/win**'
  pull_request:
    paths:
      - 'QtScrcpy/**'
      - '!QtScrcpy/res/**'
      - '.github/workflows/windows.yml'
      - 'ci/win**'
jobs:
  build:
    name: Build
    # windows-latestç›®å‰æ˜¯windows server 2022
    # windows server 2019å®‰è£…çš„æ˜¯vs2019ï¼Œwindows server 2016å®‰è£…çš„æ˜¯vs2017
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: windows-2022

    # çŸ©é˜µé…ç½® https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix
    strategy:
      matrix:
        qt-ver: [5.15.2]
        qt-arch: [win64_msvc2019_64, win32_msvc2019]
        # é…ç½®qt-archçš„é¢å¤–è®¾ç½®msvc-archï¼Œqt-arch-install
        include:
          - qt-arch: win64_msvc2019_64
            msvc-arch: x64
            qt-arch-install: msvc2019_64
          - qt-arch: win32_msvc2019
            msvc-arch: x86
            qt-arch-install: msvc2019
    # job env,æ‰€æœ‰stepséƒ½å¯ä»¥è®¿é—®
    # ä¸åŒçº§åˆ«envè¯¦è§£ https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#env
    # ä½¿ç”¨è¡¨è¾¾å¼è¯­æ³•${{}}è®¿é—®ä¸Šä¸‹æ–‡ https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
    env:
      target-name: QtScrcpy
      vcvarsall-path: 'C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat'
      vcinstall-path: 'C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC'
      qt-install-path: ${{ github.workspace }}/${{ matrix.qt-ver }}
      plantform-des: win
    # æ­¥éª¤
    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v4
        with:
          path: ${{ env.qt-install-path }}/${{ matrix.qt-arch-install }}
          key: ${{ runner.os }}/${{ matrix.qt-ver }}/${{ matrix.qt-arch }}        
      # å®‰è£…Qt
      - name: Install Qt
        # ä½¿ç”¨å¤–éƒ¨actionã€‚è¿™ä¸ªactionä¸“é—¨ç”¨æ¥å®‰è£…Qt
        uses: jurplel/install-qt-action@v4.1.1
        with:
          # Version of Qt to install
          version: ${{ matrix.qt-ver }}
          # Target platform for build
          target: desktop
          # Architecture for Windows/Android
          arch: ${{ matrix.qt-arch }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
      # æ‹‰å–ä»£ç 
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'true'
          ssh-key: ${{ secrets.BOT_SSH_KEY }}
      # ç¼–è¯‘msvc
      - name: Build MSVC
        # shellä»‹ç» https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell
        shell: cmd
        env:
          ENV_VCVARSALL: ${{ env.vcvarsall-path }}
          ENV_QT_PATH: ${{ env.qt-install-path }}
        run: |
          call python ci\generate-version.py
          call "ci\win\build_for_win.bat" RelWithDebInfo ${{ matrix.msvc-arch }}
      # èŽ·å–refæœ€åŽä¸€ä¸ª/åŽçš„å†…å®¹
      - name: Get the version
        shell: bash
        id: get-version
        # ${ GITHUB_REF/refs\/tags\// }æ˜¯linux shell ${}çš„å˜é‡æ›¿æ¢è¯­æ³•
        run: echo ::set-output name=version::${GITHUB_REF##*/}
      # tag æ‰“åŒ…
      - name: Package
        id: package
        env:
          ENV_VCVARSALL: ${{ env.vcvarsall-path }}
          ENV_VCINSTALL: ${{ env.vcinstall-path }}
          ENV_QT_PATH: ${{ env.qt-install-path }}
          publish_name: ${{ env.target-name }}-${{ env.plantform-des }}-${{ matrix.msvc-arch }}-${{ steps.get-version.outputs.version }}
        run: |
          cmd.exe /c ci\win\publish_for_win.bat ${{ matrix.msvc-arch }} ..\build\${{ env.publish_name }}
          # æ‰“åŒ…zip
          Compress-Archive -Path ci\build\${{ env.publish_name }} ci\build\${{ env.publish_name }}.zip
          echo "::set-output name=package-name::${{ env.publish_name }}"
      # ä¸Šä¼ artifacts
      # https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.package.outputs.package-name }}.zip
          path: ci\build\${{ steps.package.outputs.package-name }}
      # Upload to release
      - name: Upload Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ci\build\${{ steps.package.outputs.package-name }}.zip
          asset_name: ${{ steps.package.outputs.package-name }}.zip
          tag: ${{ github.ref }}
          overwrite: true